### ISSUE TITLE
panic err when i open nvim or htop

### ISSUE THREAD

**Issue by elbashery** [fyne-io/terminal#1]
Firstly : Thank you for this project.

**enveronment** : wayland gnome

when I try to open nvim or htop : the fyneTerm is crach whith panic runtime error
index out of range.

ther are a fiw small problims. but This is most important

**Comment by andydotxyz** [comment]
Can you please provide the error log?

**Comment by elbashery** [comment]
Sorry !. I did not pay attention to your question
this is the error:
panic: runtime error: slice bounds out of range [:2] with capacity 0

goroutine 24 [running]:
github.com/fyne-io/terminal.(*Terminal).clearScreenFromCursor(0xc0000e8000)
	/home/fedora/programs/terminal-master/escape.go:162 +0x1ec
github.com/fyne-io/terminal.(*Terminal).handleEscape(0xc0000e8000, 0xbd2eaa, 0x1)
	/home/fedora/programs/terminal-master/escape.go:20 +0x146a
github.com/fyne-io/terminal.(*Terminal).handleOutput(0xc0000e8000, 0xc000549b58, 0xaf, 0x400)
	/home/fedora/programs/terminal-master/output.go:48 +0xade
github.com/fyne-io/terminal.(*Terminal).run(0xc0000e8000)
	/home/fedora/programs/terminal-master/term.go:137 +0x78
github.com/fyne-io/terminal.(*Terminal).Run(0xc0000e8000, 0x0, 0x0)
	/home/fedora/programs/terminal-master/term.go:148 +0x4c
main.main.func1(0xc0000e8000, 0x91ff40, 0xc000076420)
	/home/fedora/programs/terminal-master/cmd/fyneterm/main.go:61 +0x2b
created by main.main
	/home/fedora/programs/terminal-master/cmd/fyneterm/main.go:60 +0x337
