### ISSUE TITLE
Feature Request: Cursor Colour

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/terminal#10]
Currently the cursor is yellow, can this be changed?

Ideally the colour could be determined by the user's preferred primary colour configured in fyne_settings

**Comment by andydotxyz** [comment]
It probably should have been primary by default to match Entry.
It could be customised through a palette of colours as has been requested from other tickets before like (#1741).
Would this ticket be resolved by changing to primary or is it a request for further customisation?

**Comment by stuartmscott** [comment]
Yes, this ticket could be resolved if the cursor used `theme.PrimaryColor()`, as the final colour could be customized via fyne_settings

**Comment by andydotxyz** [comment]
Great, Whilst at it I realised that the error colour should be from the Fyne theme as well :)

**Comment by stuartmscott** [comment]
Bonus!
