### ISSUE TITLE
Can Terminal export the Write method？

### ISSUE THREAD

**Issue by tk103331** [fyne-io/terminal#11]
I want to send commands into Terminal.

**Comment by andydotxyz** [comment]
This is a good point. What sort of content are you writing? We could expose `Write([]byte)` or `WriteString(string)`

**Comment by tk103331** [comment]
This is my project: https://github.com/tk103331/fyneshell.A shell client by fyne, for local PTY or SSH.

I want to implement the feature of quick command, which can quickly send the command to the terminal.

**Comment by andydotxyz** [comment]
That looks like a fun project. However we would appreciate it if you don't imply that the Fyne project created this - the wording "A shell client by fyne..." could be misleading.

**Comment by andydotxyz** [comment]
That should be working for you now :)

**Comment by tk103331** [comment]
Thank you for your reply. I will try it soon. 

And, I apologize for my mistake. I will update the project description. Is it appropriate to look like this: "A simple SSH client via Fyne."?

**Comment by tk103331** [comment]
I have try it.It works well in local pty,but not well in ssh connection.
When i 'Write' cmd into terminal, the cmd can send into ssh connection,but not display in the terminal.

**Comment by andydotxyz** [comment]
> Is it appropriate to look like this: "A simple SSH client via Fyne."?

Great thank you.

> Do you still need me to change the project name?

The name is less of a problem, but if people could confuse it with FyneTerm then maybe a different name would be helpful?

> When i 'Write' cmd into terminal, the cmd can send into ssh connection,but not display in the terminal.

Perhaps you have opened the SSH connection with echo turned off? I don’t think the terminal is responsible for showing what was sent to the shell inside or you’d get doubled up rendering for a local terminal.

**Comment by tk103331** [comment]
Maybe you are right.


Renamed project : https://github.com/tk103331/goshell

**Comment by andydotxyz** [comment]
> Renamed project : https://github.com/tk103331/goshell

Thanks, I appreciate that.
