### ISSUE TITLE
Please add build instructions to README.md

### ISSUE THREAD

**Issue by probonopd** [fyne-io/terminal#2]
Please add build instructions to `README.md`, thanks.

`go build -v github.com/fyne-io/terminal` did not result in a `~/go/bin/terminal` for me...

**Comment by Jacalz** [comment]
I think it might be `go install` that should be looking at using instead ;)

**Comment by probonopd** [comment]
Tried that too. Don't even get a `~/go/bin` directory...

**Comment by andydotxyz** [comment]
“Go get” is what you want.

**Comment by andydotxyz** [comment]
Also, you need the cmd/fyneterm subdirectory as the top level is the terminal library.

‘go get github.com/fyne-io/terminal/cmd/fyneterm’

**Comment by probonopd** [comment]
`go get -v github.com/fyne-io/terminal/cmd/fyneterm` ends with

```
../go/src/github.com/fyne-io/terminal/vendor/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:137:23: error: expected ';' after expression
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by andydotxyz** [comment]
Yeah, the terminal does not currently build on BSD, I’m looking at that later today.

**Comment by andydotxyz** [comment]
Added to the README and I have updated deps so this should now work on BSD, apologies that it was not the case before!

**Comment by probonopd** [comment]
Can compile now, but there is an error at runtime:

```
user@FreeBSD$ go build -u all -v github.com/fyne-io/terminal/cmd/fyneterm
user@FreeBSD$ go install  -v github.com/fyne-io/terminal/cmd/fyneterm
user@FreeBSD$ /home/user/go/bin/fyneterm 
2020/10/10 18:59:26 Fyne error:  Failure in terminal
2020/10/10 18:59:26   Cause: fork/exec /usr/local/bin/bash: Setctty set but Ctty not valid in child
2020/10/10 18:59:26   At: /home/user/go/src/github.com/fyne-io/terminal/cmd/fyneterm/main.go:70
user@FreeBSD$ /home/user/go/bin/fyneterm 
2020/10/10 19:00:39 Fyne error:  Failure in terminal
2020/10/10 19:00:39   Cause: fork/exec /usr/local/bin/bash: Setctty set but Ctty not valid in child
2020/10/10 19:00:39   At: /home/user/go/src/github.com/fyne-io/terminal/cmd/fyneterm/main.go:70
```

**Comment by andydotxyz** [comment]
Seems there was an incompatibility with some Go versions on BSD. Should be fixed now.

**Comment by probonopd** [comment]
I can confirm. Thank you very much.
