### ISSUE TITLE
terminal code can support k8s connect?

### ISSUE THREAD

**Issue by GuoRanYiMao** [fyne-io/terminal#24]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

hi there,
I want to use container.TabItem to connect k8s, I find the fyne-io/terminal can support ssh connection. It cann`t support k8s.io/client-go/tools/remotecommand .
i need help

### Describe the solution you'd like to see.

i hope fyne-io/terminal can support k8s connect

**Comment by Bluebugs** [comment]
We don't really have a direct example for exactly this, but it should be doable. The idea would be, after looking at how you use k8s remote command ( Example of k8s remote command https://github.com/fyne-io/fyne-cross/pull/120/files#diff-3473351f0592a2d0214cfc681708f2a4e95ee4d36e00e0376d2790c068e04e00R146 ), to create two io.Pipe (https://pkg.go.dev/io#Pipe) provide one side to the exec.Stream command and the other side to func (*Terminal) RunWithConnection. There is no difference between stdout and stderr from Terminal point of view, so most likely reusing the same pipe would work.

**Comment by GuoRanYiMao** [comment]
> We don't really have a direct example for exactly this, but it should be doable. The idea would be, after looking at how you use k8s remote command ( Example of k8s remote command https://github.com/fyne-io/fyne-cross/pull/120/files#diff-3473351f0592a2d0214cfc681708f2a4e95ee4d36e00e0376d2790c068e04e00R146 ), to create two io.Pipe (https://pkg.go.dev/io#Pipe) provide one side to the exec.Stream command and the other side to func (*Terminal) RunWithConnection. There is no difference between stdout and stderr from Terminal point of view, so most likely reusing the same pipe would work.

thanks alot .
