### ISSUE TITLE
terminal bug 2.1.x->2.2.x

### ISSUE THREAD

**Issue by hq-zhonger** [fyne-io/terminal#26]
2021 terminal version from version 2.1.x to version 2.2.x Can't move I have tried all versions before 2.3.x
![5](https://user-images.githubusercontent.com/78897251/217868625-9996a600-56b2-472e-9176-a0910312ccab.PNG)
![6](https://user-images.githubusercontent.com/78897251/217869190-331dc7b2-c4fa-417f-a6f0-8b6a53be5801.PNG)

The latest terminal must use the 2.3.x version, but the 2.3.x version is not compatible. My project can be compiled normally. Many controls will report too many pointer errors and cannot run. I hope the author can change the 2021 terminal to 2.1.x-2.2.x.

**Comment by hq-zhonger** [comment]
I deleted the 2023 version of go.mod and replaced the code copy into the 2021 version of the file. After compiling, it solved the problem of 2.1.x->2.2.x running stuck

**Comment by andydotxyz** [comment]
I have removed the issues to 2.0.x - those bugs have been fixed a long time ago with newer releases.

**Comment by andydotxyz** [comment]
> Many controls will report too many pointer errors and cannot run.

All versions since v2 are compile-compatible so you should not see any compilation errors.

**Comment by andydotxyz** [comment]
Also it is important to understand the difference of `Fyne` and `terminal` library, it is not clear what the error being reported is, and therefore which library is causing the problem.

**Comment by hq-zhonger** [comment]
Maybe it's because of the translation problem, some expressions are not clear after escaping
I am using the 2023 version of the terminal, which will force the update of the fyne 2.3.0 version. The fyne 2.3.0 version bug has been reported to the fyne project. You can use the 2.1.x to 2.2.x fyne to run the 2021 version of the terminal and you will find The terminal will freeze, but the problem has been solved. I deleted the go.mod in the terminal 2023 project and copied all the codes of the 2023 project to the 2021 project for replacement. After the replacement, I used fyne 2.2.4 to compile and run normally.

**Comment by andydotxyz** [comment]
With the latest terminal and Fyne code what bug are you reporting?

**Comment by andydotxyz** [comment]
With the new release of Fyne and this project now being updated I think this is resolved.
