### ISSUE TITLE
3 tips for using

### ISSUE THREAD

**Issue by hq-zhonger** [fyne-io/terminal#27]
![10](https://user-images.githubusercontent.com/78897251/217967912-486d202c-6ee3-4b87-a679-e827d823cc39.PNG)
1. Non-English garbled characters
2. Unable to get the previous content, scrolling records should be supported
3. Copy content cannot be copied like text

**Comment by andydotxyz** [comment]
Please use one issue per feature request or bug report. We cannot track multiple items against a single ticket.

**Comment by andydotxyz** [comment]
1) Should be resolved with updated version
2) Content scrolling is #32
3) Copying text is #25
