### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by squash** [fyne-io/terminal#4]
I realize this app is more of an example than something people are expected to use, but the performance is pretty low on the two systems I've tried it on. I have a terminal-ish app in mind and was looking to see how this was written, and I don't see any obvious "aha that's why it's slow" code.. For reference, in the default window size (80x25) on my Ryzen 3450 laptop, just running 'top' consumes >100% cpu and takes about 2 seconds per refresh. Any thoughts on how this could be improved?

**Comment by andydotxyz** [comment]
Mostly the performance issues are with the Fyne TextGrid widget that needs some love.
It's pretty high up my list :).

**Comment by andydotxyz** [comment]
I think it is worth re-testing as of today @squash .
Things have got much better regarding performance.
There is a lot more work to do, but I think this should be sufficient for us to consider working to a `0.1` release.
Top here consumes around 8% of the CPU that it used to. Refresh is almost instant as well.

Let me know how it goes for you.

**Comment by andydotxyz** [comment]
I'm going to close this for now as it is hugely improved. Feel free to re-open if you still have issues.
