### ISSUE TITLE
Panic upon launch

### ISSUE THREAD

**Issue by 0-issue** [fyne-io/terminal#40]
macOS Sonoma, Apple M1 Silicon

```
% go install github.com/fyne-io/terminal/cmd/fyneterm@latest
```

```
* % panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x105039628]

goroutine 7 [running]:
github.com/fyne-io/terminal.(*Terminal).setDirectory(0x14000492de8?, {0x14000608b2a, 0x10})
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/osc.go:50 +0x48
github.com/fyne-io/terminal.(*Terminal).handleOSC(0x14000492e80?, {0x14000608b28?, 0x16?})
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/osc.go:24 +0x164
github.com/fyne-io/terminal.(*Terminal).handleOutput(0x14000428000, {0x1400070e000, 0x16, 0x150024200520018?})
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/output.go:111 +0x1ec
github.com/fyne-io/terminal.(*Terminal).run(0x14000428000)
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/term.go:261 +0x140
github.com/fyne-io/terminal.(*Terminal).RunLocalShell(0x14000428000)
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/term.go:278 +0x54
main.newTerminalWindow.func5()
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/cmd/fyneterm/main.go:133 +0x30
created by main.newTerminalWindow in goroutine 1
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/cmd/fyneterm/main.go:132 +0x6e0
```

**Comment by andydotxyz** [comment]
Although the docs are a little out of date they do indicate that you need to be in the cmd/fyneterm package to build the binary.

**Comment by andydotxyz** [comment]
What happens if you grant the application access to your home folder in system settings and try to run it again?

**Comment by andydotxyz** [comment]
Maybe build and install it with "fyne install" then run it from /Applications. Maybe then it prompts or can be bestowed permission

**Comment by andydotxyz** [comment]
Yup, i wondered if that was the case - did it ask you to permit it to access the home directory?

I wonder why CLI apps work but locally compiled binaries aren't working...

Will see if I can replicate by upgrading our test rig.

**Comment by andydotxyz** [comment]
I have now managed to replicate this and can share that it's not a permission issue but relates to macOS gatekeeper.
For some reason it is denying the raw binary from running. But it is quite happy with the packaged binary. Very strange and rather frustrating!

We will have to resolve this fast!

**Comment by andydotxyz** [comment]
The Go team / triage have marked this as an issue with Apple macOS and not an issue with Go. I am not sure what we can do as a result...

**Comment by andydotxyz** [comment]
I can no longer replicate - I wonder if Go or macOS has fixed an underlying issue...
Using Go 1.20.9 and macOS 14.0 (update 23A344) works for me - what about you @0-issue ?
