### ISSUE TITLE
Read text from Terminal?

### ISSUE THREAD

**Issue by figuerom16** [fyne-io/terminal#48]
Looking for a way to read text displayed on terminal.
~~Being able to read last n number of characters displayed on terminal would be ideal.  output, err := t.ReadLast(n int)~~

EDIT:  Getting access to t.content.Text() would be perfect as that's already created.

**Comment by andydotxyz** [comment]
That's a good suggestion. As the code is in place perhaps you are able to open a small PR to call through to that method?

**Comment by figuerom16** [comment]
Created PR #49

**Comment by andydotxyz** [comment]
Thanks, the PR is now landed
