### ISSUE TITLE
Generic terminal widget

### ISSUE THREAD

**Issue by tk103331** [fyne-io/terminal#5]
Can a generic terminal widget be provided without internal PTY binding?
Instead, it can provides a way to bind, either to a PTY or an SSH connection. This makes it easy to implement an SSH client.

**Comment by andydotxyz** [comment]
That is a great idea.
Any idea how you would like that interface to be made available? I guess it would be a parameter to the `Terminal` constructor?

**Comment by andydotxyz** [comment]
I think we could support passing a `*File` in, which would refer to the underlying FD.

**Comment by tk103331** [comment]
File can be used for read and write, but is there any other necessary behavior, such as resize? I'm not sure.

**Comment by andydotxyz** [comment]
The resize commands are sent as escape sequences to the terminal at the other end.
Do you have an SSH connection library / app that I could experiment with to try out the idea?

**Comment by tk103331** [comment]
Sorry for the late reply. 

I want to make a simple terminal application that supports local PTY and SSH connections, just like a simple version of SecureCRT. I have tried Flutter, but I don't know much about Dart, the progress is slow. Now I found Fyneterm and am trying to use it.

The Flutter project:https://github.com/TerminalStudio/lite.

**Comment by tk103331** [comment]
I didn't have much experience in interface rendering and terminal technology, just wanted to make an easy to use application. I have some experience with Go, and I liked and liked Fyne in the Go GUI library. I happened to see the Fyneterm project, so I wanted to see if I could use Fyne.

It would be great nice if Fyne could provide an easy-to-use Terminal widget.

**Comment by andydotxyz** [comment]
OK, cool. So there is some good news :).

I managed to take the following screenshot of an active SSH connection through this terminal (with some local changes).
It does not manage to pass resize information through the channel (yet) but it feels like a good start.

<img width="912" alt="Screenshot 2021-04-07 at 09 50 46" src="https://user-images.githubusercontent.com/294436/113838573-cca96f00-9786-11eb-9a04-7afc711f97db.png">

The code ended up looking something like this:

```go
	t := terminal.NewTerminal()
	a := app.New()
	w := a.NewWindow(termTitle)
	w.SetContent(t)

	// ssh setup omitted, summary is:
	conn, err := ssh.Dial("tcp", "localhost:22", config)
	session, err := conn.NewSession()
	session.RequestPty("xterm-color", 24, 80, modes)
	// end ssh summary

	in, err1 := session.StdinPipe()
	out, err2 := session.StdoutPipe()
	// omitted error handling

	go session.Run("$SHELL || bash")
	go func() {
		err := t.RunWithConnection(in, out)
	}

	w.ShowAndRun()
```

Does that fit the bill? If I can add the refactoring that allows for simple input/output stream connection this all becomes possible :)

**Comment by tk103331** [comment]
That's great. 
I think that's enough to meet my needs. Thank you for your support.

**Comment by andydotxyz** [comment]
Great, that is in now.
I have some local code that pulls together an SSH connection.
I was considering adding it to the repo here as a "fynessh" app, but I didn't want to step on your toes ;).

https://github.com/fyne-io/terminal#library
