### ISSUE TITLE
RFE: Expose exit code from Terminal's shell

### ISSUE THREAD

**Issue by schnoddelbotz** [fyne-io/terminal#72]
Hi and thanks for fyne + terminal.

For my use-case it would be very helpful to retrieve the final exit code from the terminal's shell to determine outcome from commands executed in terminal via `write()`.

The attached screenshot shows required changes to make this work (at least on macOS).
It obviously lacks Windows support so far and has no tests - I wanted to check your general thoughts on this before proceeding.

Should you be positive on it, feel free to simply recycle bits from below - or let me know if you'd prefer a PR.
👋

<img width="716" alt="terminal-diff" src="https://github.com/fyne-io/terminal/assets/2153919/6cdf6282-de1b-493f-8e35-c5e51797d861">

**Comment by andydotxyz** [comment]
This could be a good change. I don't see any reason it would not be OK to add it,
As you guessed PR is the way to add features to the repo, also with more safety in case the `ExitCode` is called before process exited.

Probably some documentation too

**Comment by schnoddelbotz** [comment]
Thanks for the quick response - PR done, including Windows support (tested, seems OK), a tiny test and README update.
Given even the screenshots prove that Windows is supported, I also dropped it from TODO section.
Note the repository's "About" message should be enhanced with macOS and Windows, too, IMHO.

**Comment by schnoddelbotz** [comment]
Thanks for merging. I just noticed my change dropped coverage by 0.02%.
Made me feel a bit bad ;) thus I attempted to fix it by adding a test for exit codes 0 and 1:
https://github.com/schnoddelbotz/terminal/commit/8633352e52cfac3e7b32392d7e9dc9ca6feab0f1
Please just ping me if you consider it worth a PR  🥂

**Comment by andydotxyz** [comment]
That would be nice thanks - always good to keep the coverage increasing :)

**Comment by andydotxyz** [comment]
Closing this as the main fix is in, thanks @schnoddelbotz
