### ISSUE TITLE
Allow setting the command that the terminal should run on start

### ISSUE THREAD

**Issue by obvionaoe** [fyne-io/terminal#79]
Hi, I'm trying to make a simple terminal window that automatically runs a TUI.
So I'd like to pass the TUI as the command instead of the default shell.
Can the command be made into a public property?

Thanks

**Comment by andydotxyz** [comment]
This is already possible. Instead of `RunLocalShell` (which runs an interactive shell) you should use the `RunWithConnection` constructor - it is illustrated in the README file as well.

**Comment by obvionaoe** [comment]
Thanks, I missed that on my first look, but is there no way to run an arbitrary command without the overhead of an SSH session?

**Comment by andydotxyz** [comment]
My apologies, I was not meaning to suggest running through ssh..
It is an illustration that any command can be run, just hook up the input and output streams

**Comment by obvionaoe** [comment]
Ah my bad, I thought it required SSH, but the streams are the things being passed. Thank you :bowing_man:

**Comment by fkollmann** [comment]
I use the following hack to do this:

```go
t.SetReadWriter(terminal.ReadWriterConfiguratorFunc(func(r io.Reader, w io.WriteCloser) (io.Reader, io.WriteCloser) {
	w.Write([]byte(fmt.Sprintf("cd '%v' && ", service.CommandStartDirectory)))
	w.Write([]byte(service.CommandStart))
	w.Write([]byte(" ; exit\n")) // exit terminal if service exits

	return r, w
}))
```
