### ISSUE TITLE
Need support of cut&paste inside terminal window

### ISSUE THREAD

**Issue by naiming-zededa** [fyne-io/terminal#80]
I'm using fyne v2.4.4, and latest terminal of fyne-io.
When inside my App, when launching a terminal window, I can NOT do
Cut&Paste operation. I have tried on MacOS and Linux, the same problem.
Andrew suggested maybe this was a Focus issue, and I have added this in
the code like:
```
        t := terminal.New()
	win.SetContent(t)
	win.Resize(fyne.NewSize(1000, 700))
	win.Canvas().Focus(t)
	win.Show()
```
No difference. Using MacOS Cmd-C/Cmd-V does not do anything inside termianl window.
I'm not talking about cut&paste between the desktop and this terminal, but only within
the terminal itself at this point.

**Comment by figuerom16** [comment]
I was able to copy and paste in the terminal in Linux with the latest fyne terminal in my app by using CTRL+SHIFT+C and CTRL+SHIFT+V.  Could you try those key combinations?

**Comment by naiming-zededa** [comment]
> I was able to copy and paste in the terminal in Linux with the latest fyne terminal in my app by using CTRL+SHIFT+C and CTRL+SHIFT+V. Could you try those key combinations?

yes, I'm also able to do this with the above keys on the Linux OS. But i can not do this on the MacOS app.

**Comment by naiming-zededa** [comment]
I tried on window OS, the CTRL+SHIFT+C and CTRL+SHIFT+V worked for me also. So, the MacOS is the only desktop OS which I can not do.

**Comment by figuerom16** [comment]
Sorry I don't own a Mac so I can't see what's happening.  Hopefully someone who has one can help with the last part.

**Comment by andydotxyz** [comment]
I thought I knew the issue but I was wrong. In fact I cannot replicate this issue at all...

**Comment by andydotxyz** [comment]
> I tried on window OS, the CTRL+SHIFT+C and CTRL+SHIFT+V worked for me also. So, the MacOS is the only desktop OS which I can not do.

It is actually working perfectly on my macOS tests.
You're not using a windows keyboard on a Mac are you? Or other strange combination?

In my tests the Cmd (⌘) + C and V works perfectly

**Comment by naiming-zededa** [comment]
> > I tried on window OS, the CTRL+SHIFT+C and CTRL+SHIFT+V worked for me also. So, the MacOS is the only desktop OS which I can not do.
> 
> It is actually working perfectly on my macOS tests. You're not using a windows keyboard on a Mac are you? Or other strange combination?
> 
> In my tests the Cmd (⌘) + C and V works as expected.

No that was not a keyboard problem. The thing is that i forgot I actually copied come this terminal code (in order to customized the color is the shell, the directory color of blue in dark mode problem), maybe I have missed some files or functions. I'll close this issue. I have verified now with the sample terminal, I'm able to do cut&paste on the macOS. Thanks.
