### ISSUE TITLE
Is it possible to set a custom font for only the terminal window?

### ISSUE THREAD

**Issue by Gys** [fyne-io/terminal#82]
I would like to set a custom font for only the (window with the) terminal widget. I did some searching and was able to change font and colors by changing the general theme. But it seems it is not possible to set the font for one widget only? 

Maybe this is more of a general Fyne question. But as I specifically would like to change (only) the terminal widget I posted it here.

**Comment by andydotxyz** [comment]
Not at this time - it uses the monospace font from the theme. You could use a custom theme to change only the monospace font.

In 2.5 there is a new "ThemeOverride" container that will support forcing a certain theme to an area of the app which will enable what you describe.
